### ISSUE TITLE
research popular repos w/ models and how they're architected

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_job_quality#9]
[Google doc](https://docs.google.com/document/d/1OKxSSMKCLxLabMDFRTipk0_T4tpLFkw_qF5CGCDIslg/edit)

**Comment by Jack-Vines** [comment]
- How do they deal with large model files (e.g. spaCy, nltk, scikit-learn)
- What are features of "good" libraries (not necessarily model repos)
- (more difficult) are there any good examples of smaller/more research-y repos and how are they architected?
- are there any repos made for the SRS?
